icanbwell/fhir-server

package.json
src/config.js
src/middleware/sentry.js

Will need the following environment variable
SENTRY_DSN=GET_FROM_NATHAN

HDE-588 - Add Sentry for Error Tracking

---

package.json
src/app.js
src/utils/prometheus.utils.js

visit /metrics for an export of prometheus info
you can add additional metrics in ./src/utils/prometheus.utils.js

Prometheus Metrics

---

src/oauth/callback.html

Added samesite option for cookie to block CSRF

MRC-453: Minor update to cookie expiration time using JWT exp time.

---

src/operations/graph/graphHelpers.js
src/tests/practitioner/graph_pss_organization/fixtures/expected/expected.json
src/tests/practitioner/graph_pss_organization/fixtures/expected/expected_hash_references.json
src/tests/practitioner/graph_pss_organization/fixtures/graph/my_graph.json
src/tests/practitioner/graph_pss_organization/fixtures/practitioner/healthcareService.json
src/tests/practitioner/graph_pss_organization/fixtures/practitioner/location.json
src/tests/practitioner/graph_pss_organization/fixtures/practitioner/organization.json
src/tests/practitioner/graph_pss_organization/fixtures/practitioner/schedule.json
src/tests/practitioner/graph_pss_organization/organization.graph_pss.test.js

the issue is that there are Locations and HealthcareService as parents in the graph. We need to filter the childEntities to the current graph node we're processing.

fix bug with organization graph query

---

package-lock.json
package.json
src/app.js
src/dist/css/app.css
src/dist/js/authhandler.js
src/routeHandlers/logout.js
src/views/partials/header.ejs
src/views/partials/searchForm.ejs

- Fixed the logout button/logic
- Increased info modal size to XL
- Removed truncate/ellipses of long strings in table cells
- Added additional null checks in the search form partial

MRC-1208 custom query parameters

---

src/operations/merge/merge.js

MRC-1361: Convert lastUpdated to string if it comes in as an actual date

---

src/dist/css/app.css
src/operations/query/r4.js
src/utils/searchForm.util.js
src/views/pages/Account.ejs
src/views/pages/Appointment.ejs
src/views/pages/AuditEvent.ejs
src/views/pages/CareTeam.ejs
src/views/pages/Condition.ejs
src/views/pages/Coverage.ejs
src/views/pages/Encounter.ejs
src/views/pages/ExplanationOfBenefit.ejs
src/views/pages/HealthcareService.ejs
src/views/pages/InsurancePlan.ejs
src/views/pages/Library.ejs
src/views/pages/Location.ejs
src/views/pages/MeasureReport.ejs
src/views/pages/Observation.ejs
src/views/pages/Organization.ejs
src/views/pages/OrganizationAffiliation.ejs
src/views/pages/Patient.ejs
src/views/pages/Person.ejs
src/views/pages/Practitioner.ejs
src/views/pages/PractitionerRole.ejs
src/views/pages/Schedule.ejs
src/views/pages/SearchResult.ejs
src/views/pages/ServiceRequest.ejs
src/views/pages/Slot.ejs
src/views/pages/ValueSet.ejs
src/views/pages/index.ejs
src/views/partials/noResults.ejs

This PR is actually for two branches. The feature branch should be reviewed for the future merge into master. This `search-cleanup` branch is an attempt to keep the PRs smaller and more frequent. Thanks much.

Search form updates

---

src/operations/search/search.js
src/utils/searchForm.util.js

Feature search result list

---

src/operations/search/searchManager.js
src/tests/practitioner/search_all_return_total/fixtures/expected/expected_practitioner.json
src/tests/practitioner/search_by_id_above/fixtures/expected/expected_single_practitioner.json
src/tests/practitioner/search_return_specific_elements/fixtures/expected/expected_practitioner_bundle.json

@DarylCheung @KyleC-Bwell This was a missed requirement. I got more info from Adam Davis after the last dev deploy.

ATHD-780: Add full for 'next' relation in bundle

---

src/createContainer.js
src/operations/merge/mergeManager.js
src/operations/security/scopesManager.js
src/operations/security/scopesValidator.js
src/tests/operations/security/fixtures/task1.json
src/tests/operations/security/task_with_noauth.test.js
src/utils/configManager.js

EFS-105
Add configManager to drive authEnabled check for scopes and implement test to verify noauth behavior.

Add testability for noauth

---

Makefile
package.json
src/operations/query/filters/aboveAndBelow.js
src/operations/query/filters/contains.js
src/operations/query/r4.js
src/tests/operations/query/r4/r4.test.js
src/tests/searchParameters/search_by_identifier/search_by_identifier.test.js

EFS-84
Rearrange logic for building the search query to hav emodifiers apply after type-based logic has been applied.
Also modify loop to operate over args instead of over all possible properties.

EFS-84 Refactor search to enable modifier and type combinations

---

security.md
src/fhir/patientFilterManager.js

EFS-127
Add ChargeItemDefinition to list of resources that are not associated with a patient and can be accessed by any patient
[EFS-127]: https://icanbwell.atlassian.net/browse/EFS-127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Make ChargeItemDefinition accessible to private scope

---

src/operations/query/filters/string.js

1. Updated usage of name query builders on the basis of field type instead of field name.
2. Updated index hint columns.

CVP-1594: Fixed HumanName filtering index hints

---

src/admin/scripts/indexCollections.js
src/indexes/customIndexes.js
src/indexes/indexManager.js
src/tests/indexers/synchronizeIndex/synchronizeIndex.test.js

Ticket: https://icanbwell.atlassian.net/browse/CVP-1595
use command
```
node src/admin/scripts/indexCollections.js --synchronize
```

CVP-1595: Fix indexing script + reverse sort date based indices

---

cheatsheet.md
src/fhir/generator/fhir_xml_schema_parser.py
src/graphql/v1/generator/fhir_xml_schema_parser.py
src/indexes/indexManager.js
src/operations/query/filters/dateTime.js
src/operations/search/searchManager.js
src/tests/customMatchers.js
src/utils/bwellPersonFinder.js

SonarQube issues: https://sonarqube.services.icanbwell.com/project/issues?id=icanbwell_fhir-server&issues=AYWX0PUcn0zoDOI5r3_E&open=AYWX0PUcn0zoDOI5r3_E

CVP-1686: Fixed SonarQube blocker and major issues

---

src/tests/utils/bwellPersonFinder/bwellPersonFinder.test.js

Fixed code smells: https://sonarqube.services.icanbwell.com/project/issues?id=icanbwell_fhir-server&open=AYYX3erkn0zoDOI5OFxc&resolved=false&severities=BLOCKER

CVP-1705 Fix assertion SonarQUbe code smells

---

src/dataLayer/databaseBulkInserter.js
src/graphql/v1/resolvers/custom/patient.js
src/graphql/v2/resolvers/custom/patient.js
src/middleware/fhir/base/base.service.js
src/operations/graph/graphHelpers.js
src/operations/query/filters/token.js
src/operations/search/searchBundle.js
src/operations/search/searchManager.js
src/partitioners/partitioningManager.js
src/routeHandlers/admin.js
src/utils/assertType.js
src/utils/auditLogger.js
src/utils/memoryManager.js
src/utils/querybuilder.util.js
src/utils/rethrownError.js

https://sonarqube.services.icanbwell.com/project/issues?id=icanbwell_fhir-server&languages=js&resolved=false&severities=MAJOR

CVP-1695 Fix major code smells reported by SonarQube

---

src/fhir/generator/fhir_xml_schema_parser.py
src/fhir/generator/generate_classes.py
src/fhir/generator/generate_classes_index.py
src/fhir/generator/generate_graphql_classes.py
src/fhir/generator/test_generator.py
src/graphql/v1/generator/fhir_xml_schema_parser.py
src/graphql/v1/generator/generate_classes.py
src/graphql/v1/generator/test_generator.py

Ticket: https://icanbwell.atlassian.net/browse/CVP-1696
Sonarqube issues: https://sonarqube.services.icanbwell.com/project/issues?id=icanbwell_fhir-server&languages=py&resolved=false&severities=MAJOR

CVP-1696 Removed commented code & fixed builtin variable shadowing issue

---

src/admin/adminLogger.js
src/admin/adminPersonPatientLinkManager.js
src/app.js
src/enrich/providers/proxyPatientReferenceEnrichmentProvider.js
src/middleware/fhir/base/base.service.js
src/middleware/fhir/fhirResponseWriter.js
src/operations/common/logging.js
src/operations/merge/mergeManager.js
src/utils/changeEventProducer.js

https://sonarqube.services.icanbwell.com/project/issues?id=icanbwell_fhir-server&languages=js&resolved=false&rules=javascript%3AS4144&severities=MAJOR

CVP-1695 Fix duplicate function  reported by SonarQube

---

src/constants.js
src/graphql/v2/dataSource.js
src/tests/graphql/carePlan/fixtures/carePlans.json
src/tests/graphql/carePlan/fixtures/expected_carePlans.json
src/tests/graphql/carePlan/fixtures/query.graphql
src/tests/graphql_embeddables/medicationRequest/fixtures/expected/expected_medicationrequest.json

Ticket: https://icanbwell.atlassian.net/browse/EFS-161

EFS-161 Populate references in graphql response with reference data

---

src/admin/runners/constants.js
src/admin/runners/fixMultipleSourceAssigningAuthorityHistoryRunner.js
src/admin/runners/fixMultipleSourceAssigningAuthorityRunner.js
src/admin/scripts/fixMultipleSourceAssigningAuthority.js
src/admin/scripts/fixMultipleSourceAssigningAuthorityHistory.js
src/admin/utils/fixMultipleSourceAssigningAuthority.js
src/tests/admin/runners/fixMultipleSourceAssigningAuthority/fixMultipleSourceAssigningAuthority.test.js
src/tests/admin/runners/fixMultipleSourceAssigningAuthority/fixtures/Practitioner/practitioner1.json
src/tests/admin/runners/fixMultipleSourceAssigningAuthority/fixtures/Practitioner/practitioner1_history.json
src/tests/admin/runners/fixMultipleSourceAssigningAuthority/fixtures/Practitioner/practitioner2.json
src/tests/admin/runners/fixMultipleSourceAssigningAuthority/fixtures/Practitioner/practitionerrole1.json
src/tests/admin/runners/fixMultipleSourceAssigningAuthority/fixtures/Practitioner/practitionerrole2.json
src/tests/admin/runners/fixMultipleSourceAssigningAuthority/fixtures/expected/expected_practitioner1.json
src/tests/admin/runners/fixMultipleSourceAssigningAuthority/fixtures/expected/expected_practitioner1_hisory.json
src/tests/admin/runners/fixMultipleSourceAssigningAuthority/fixtures/expected/expected_practitioner1_hisory_in_database_before_run.json
src/tests/admin/runners/fixMultipleSourceAssigningAuthority/fixtures/expected/expected_practitioner2.json
src/tests/admin/runners/fixMultipleSourceAssigningAuthority/fixtures/expected/expected_practitioner_1_in_database_before_run.json
src/tests/admin/runners/fixMultipleSourceAssigningAuthority/fixtures/expected/expected_practitioner_2_in_database_before_run.json
src/tests/admin/runners/fixMultipleSourceAssigningAuthority/fixtures/expected/expected_practitionerrole1.json
src/tests/admin/runners/fixMultipleSourceAssigningAuthority/fixtures/expected/expected_practitionerrole2.json
src/tests/admin/runners/fixMultipleSourceAssigningAuthority/fixtures/expected/expected_practitionerrole_1_in_database_before_run.json
src/tests/admin/runners/fixMultipleSourceAssigningAuthority/fixtures/expected/expected_practitionerrole_2_in_database_before_run.json

Scripts to run:
1. Fix Practitioner resources:
`NODE_OPTIONS=--max_old_space_size=8192 node --max-old-space-size=8192 src/admin/scripts/fixMultipleSourceAssigningAuthority.js --collections=Practitioner_4_0_0 --batchSize=10000
`
2. Fix Practitioner references:
`NODE_OPTIONS=--max_old_space_size=8192 node --max-old-space-size=8192 src/admin/scripts/fixReferenceSourceAssigningAuthority.js --collections=Account,AllergyIntolerance,Appointment,CarePlan,CareTeam,ChargeItem,Claim,Communication,Condition,Consent,Contract,CoverageEligibilityRequest,CoverageEligibilityResponse,DiagnosticReport,DocumentReference,Encounter,EnrollmentRequest,EpisodeOfCare,ExplanationOfBenefit,Flag,Group,ImagingStudy,Immunization,Invoice,MeasureReport,MedicationAdministration,MedicationDispense,MedicationRequest,Medicati …

EFS-219 Add script to fix Practitioners with multiple owners

---

src/admin/runners/fixPersonLinksRunner.js
src/admin/scripts/fixPersonLinks.js
src/tests/admin/runners/fixPersonLinks/fixMultiplePersonLinks.test.js
src/tests/admin/runners/fixPersonLinks/fixtures/Patient/linkedPatient1.json
src/tests/admin/runners/fixPersonLinks/fixtures/Person/linkedPerson1.json
src/tests/admin/runners/fixPersonLinks/fixtures/Person/linkedPerson2.json
src/tests/admin/runners/fixPersonLinks/fixtures/Person/linkedPerson3.json
src/tests/admin/runners/fixPersonLinks/fixtures/Person/mainPerson1.json
src/tests/admin/runners/fixPersonLinks/fixtures/expected/expected_person1.json

Remove links of Persons that do not match the current Person either using email or name.
`
NODE_OPTIONS=--max_old_space_size=8192 node --max-old-space-size=8192 src/admin/scripts/fixPersonLinks.js --batchSize=10000 --preLoadCollections Person_4_0_0
`

EFS-228 Script to fix too many Person links

---

src/admin/scripts/dbStats.js

1. Remove dotenv requirement/import from dbStats script.
2. Run dbStats script as k8s job using deploy pipeline GHA Workflow.

EFS-250 Run admin script inside eks pod

---

src/app.js
src/views/partials/header.ejs

Updating page header to show environment and version

Dc efs 257

---

src/middleware/graphql/plugins/graphqlValidateMissingVariableValuesPlugin.js
src/tests/graphql/field_filter/field_filter.test.js

Added flag to determine when to validate GQL variables

EFS-216 Add condition for GraphQL variable validation

---

src/tests/graphql/patient/fixtures/patient_with_photo.json
src/tests/graphql/patient/fixtures/query_patient_with_gridfs.graphql
src/tests/graphql/patient/patient.gridfs.test.js

Added graphql testcases for fetching attachment data when gridfs is enabled

EFS-188 Added graphql testcases for attachment retrieval

---

src/admin/runners/runPreSaveRunner.js
src/admin/scripts/runPreSave.js
src/tests/admin/runners/runPreSave/fixtures/Patient/patient8.json
src/tests/admin/runners/runPreSave/fixtures/expected/expected_patient8.json
src/tests/admin/runners/runPreSave/fixtures/expected/expected_patient_8_in_database_before_run.json
src/tests/admin/runners/runPreSave/runPreSave.test.js

Added afterLastUpdatedDate to runPreSave Script to process records created after a particular date

EFS-281 Added afterLastUpdatedDate to runPreSave script

---

src/tests/utils/mongoCollectionManager/mongoCollectionManager.test.js
src/utils/mongoCollectionManager.js

Implemented collectionName caching to check if collectionExists or not to reduce db hits by almost 50%

EFS-269 Implemented collectionName caching in mongoCollectionManager to reduce db hits

---

src/createContainer.js
src/tests/utils/mongoCollectionManager/mongoCollectionManager.test.js
src/utils/mongoCollectionManager.js

Added exisitng collections to collectionCache on first call of getOrCreateCollection

EFS-269 Added existing collections to collectionCache

---

src/views/pages/Observation.ejs
src/views/partials/referenceRange.ejs

EFS-310 Added Reference Range and Effective Period to observation pagee in fhir UI

---

src/dataLayer/databaseBulkInserter.js
src/utils/auditLogger.js

created insertOneAuditEvent async function to insert audit event logs rather than upserting audit event logs

EFS-303 Created insertOneAuditEventAsync to insert audit event

---

src/dataLayer/databaseBulkInserter.js
src/utils/auditLogger.js

Reverts icanbwell/fhir-server#1017

Revert "EFS-303 Created insertOneAuditEventAsync to insert audit event"

---

CONTRIBUTING.md
src/admin/runners/indexCollectionsRunner.js
src/admin/scripts/indexCollections.js
src/indexes/customIndexes.js
src/indexes/indexManager.js
src/tests/indexers/addMissingIndex/addMissingIndex.test.js
src/tests/indexers/addMissingIndex/mockCustomIndexes.js
src/tests/indexers/removeExtraIndex/mockCustomIndexes.js
src/tests/indexers/removeExtraIndex/removeExtraIndex.test.js

- Added missingIndexesOnly flag to add missing indexes only
- Added extraIndexesOnly flag to remove extra indexes only
- Changed synchronize flag to remove and add indexes collection by collection
- Changed index names in customIndexes to contain collection name as prefix

EFS-368 added missingOnly and extraOnly flag to indexCollections script and changed synchronize

---

Makefile
docker-compose.yml
package-lock.json
package.json
src/admin/adminLogManager.js
src/admin/runners/baseScriptRunner.js
src/admin/runners/indexCollectionsRunner.js
src/admin/scripts/indexCollections.js
src/constants.js
src/indexes/customIndexes.js
src/indexes/indexManager.js
src/routeHandlers/admin.js
src/utils/fhirLogger.js
src/utils/mongoDatabaseManager.js
yarn.lock

- Removed ES related code from fhir server
- Removed ES and kibana docker
- Added index for access logs collection
- Updated indexCollections script to support access_logs cluster

EFS-412 Removed ES code from fhir server and added meta.id index for access logs

---

src/admin/runners/fixReferenceIdRunner.js
src/admin/runners/fixReferenceIdThedacareRunner.js
src/tests/admin/runners/fixReferenceIdThedacare/fixReferenceId.Mock.test.js

- fixed counting error from fixReferenceId script
- fixed Mock thedacare testcase

EFS-393 Fixed counting error

---

src/createContainer.js
src/fhir/patientFilterManager.js
src/operations/search/searchManager.js

EFS-432 Add function isPatientRelatedResource to check if resource is related to patient

EFS-432 Add function isPatientRelatedResource to check if resource is related to patient

---

src/operations/search/searchManager.js

EFS-432 Add functionality to getResourceIdsFromFilter for patientIds from query

EFS-432 Add functionality to getResourceIdsFromFilter for patientIds from query

---

src/admin/runners/fixReferenceIdRunner.js
src/admin/utils/fixMultipleSourceAssigningAuthority.js
src/tests/questionnaireResponse/search_by_id/fixtures/expected_questionnaire_responses.json
src/tests/questionnaireResponse/search_by_id/fixtures/questionnaire_responses.json
src/tests/questionnaireResponse/search_by_id/search_by_id.test.js
src/tests/searchParameters/search_by_name/search_by_name.test.js
src/utils/getDefaultSortIdValue.js
src/utils/querybuilder.util.js
yarn.lock

In FHIR R4, there was an error where the identifier field on QuestionnaireResponse is 0..1 instead of 0..* like it is on every resource: http://hl7.org/fhir/R4/questionnaireresponse.html.  They fixed this in R4B.  But we have to handle it in our code.  Some new code was not handling it and throwing errors.

EFS-464: Check that identifier is an array

---

src/admin/runners/dumpPersonsRunner.js
src/admin/scripts/dumpPersons.js

add page sizing and json formatting

Dc efs 434 2 

---

.github/workflows/aikido.yml

Adding Aikido Security scanning to PRs

Add Aikido Security to scan PRs

---

src/operations/update/update.js
src/tests/searchParameters/search_by_date/search_by_date.test.js
src/tests/update/put_response/put_response.test.js
src/utils/querybuilder.util.js

- fixed error on update when id is not present in resource and _validate param is sent
- added validation error if date value sent is not in proper format in search

EFS-490 Fixed some bugs

---

package.json
src/middleware/graphql/graphqlServer.js
yarn.lock

This work belongs to the [Bwell SDK initiative](https://icanbwell.atlassian.net/browse/EA-506). 
https://icanbwell.atlassian.net/browse/EA-577

EA-577 fhir server as subgraph on supergraph

---

src/fhir/generator/fhir_xml_schema_parser.py

Ran `make graphql` and `make classes` to verify no impact.

EFS-505 Replaced Python assert with Exception

---

src/graphql/v2/dataSource.js
src/graphql/v2/resolvers/custom/careTeam.js
src/graphql/v2/resolvers/custom/patient.js
src/operations/fhirOperationsManager.js
src/tests/update/put_response_with_proxy_patient/expected/expected_patient.json
src/tests/update/put_response_with_proxy_patient/fixtures/patient.json
src/tests/update/put_response_with_proxy_patient/fixtures/person.json
src/tests/update/put_response_with_proxy_patient/put_proxy_patient.test.js

Disabled proxy-patient to patient expander in graphql mutations and REST api's post/put/patch/delete etc request
Please check this comment for more info: https://github.com/icanbwell/fhir-server/pull/1270#discussion_r1345457337

EFS-598 Correct sentry error, disable proxy-patient expansion for requests other than searching

---

src/operations/update/update.js

Sample access log generated
```
{
"_id": {
"$oid": "653245f955295a0d8fc7131d"
},
"timestamp": {
"$date": "2023-10-20T09:18:49.689Z"
},
"level": "info",
"message": "operationCompleted",
"meta": {
"id": "426e52ca-043b-4a3e-9e15-71548747770a",
"type": {
"code": "operation"
},
"action": "update",
"period": {
"start": "2023-10-20T09:18:49.669Z",
"end": "2023-10-20T09:18:49.686Z"
},
"recorded": {
"$date": "2023-10-20T09:18:49.000Z"
},
"outcome": 0,
"outcomeDesc": "Success",
"agent": [
{
"type": {
"text": "bwell"
},
"altId": "mintu.sah",
"network": {
"address": "::ffff:172.19.0.1"
},
"policy": [
"openid",
"profile",
"email",
"access/*.*",
"admin/*.*",
"user/*.*"
]
}
],
"source": {
"site": "/4_0_0/Patient/a00c6ec8-7733-4794-a2e1-003693efa289"
},
"entity": [
{
"name": "Patient",
"detail": [
{ …
```

EFS-644 Log operation outcome whene no change in resource while updating

---

src/partitioners/partitioningManager.js
src/utils/auditLogger.js

Reverts icanbwell/fhir-server#1310

Revert "EFS-642 Removed mutex from auditLogger"

---

src/partitioners/partitioningManager.js
src/utils/auditLogger.js

Reverts icanbwell/fhir-server#1312

Revert "Revert "EFS-642 Removed mutex from auditLogger""

---

src/fhir/patientFilterManager.js
src/indexes/customIndexes.js

2 issues fixed here:
1. Slow Communication DB queries.
2. Error for Bundle resource not being accessible through patient scoped token.

EFS-692 Add Bundle to non-patient resource list and add index for Communication

---

docker-compose.yml
src/strategies/jwt.bearer.strategy.js

Reverts icanbwell/fhir-server#1372

Revert "EFS-720 using username from JWT as personid"

---

src/app.js
yarn.lock

Added a Request Completed log which prints statusCode, userAgent, requestUrl, responseTime, method, and scope.
Here is the sequence in which logs can be expected for different status codes:
200/201 - Incoming Request, operation logs, Operation Completed, Request Completed
400 - Incoming Request, operation logs, Request Completed
401 - Incoming Request, Request Completed
500 - Incoming Request, operation logs, and error logs, Request Completed

EFS-753 Added Request Completed log

---

src/admin/runners/fixConsentRunner.js
src/admin/scripts/fixConsent.js

Fix missing Consent Category code and Provision class

Dc efs 801

---

src/graphql/dataSource.js
src/graphql/resolvers/custom/codeSystemProperty1.js
src/tests/graphql/communication/fixtures/query.graphql
src/tests/graphql/person/fixtures/expected_graphql_person_response.json
src/tests/graphql/person/fixtures/query_person.graphql
src/tests/graphql/person/person.test.js

Reverts icanbwell/fhir-server#1546

Revert "EFS-943 Fixed query for graphql"

---

src/operations/create/create.js
src/operations/merge/merge.js
src/operations/merge/mergeManager.js
src/operations/patch/patch.js
src/operations/remove/remove.js
src/operations/update/update.js

Added logs to count number of resources created, updated, deleted, failed on validation, and not changed
Log format
```
{
"id": "1",
"level": "info",
"logger": "default",
"message": "Resource Created",
"operation": "merge",
"request": {
"id": "bae815be-3d25-46e5-adee-a2c24ee1eece",
"systemGeneratedRequestId": "bae815be-3d25-46e5-adee-a2c24ee1eece"
},
"resourceType": "Observation",
"sourceAssigningAuthority": "bwell",
"timestamp": "2024-05-02T10:30:08+00:00",
"uuid": "61abdd48-df46-5e98-ac6c-fde3cace4d07",
"version": null
}
```

EFS-955 Added log to check created, updated, validated, and no change resources at grafana

---

export.md
src/admin/adminExportManager.js
src/fhir/classes/4_0_0/custom_resources/exportStatus.js
src/middleware/fhir/fhirResponseWriter.js
src/operations/export/export.js
src/operations/export/exportManager.js
src/operations/export/script/bulkDataExport.js
src/operations/export/script/bulkDataExportRunner.js
src/operations/export/script/cronJobRunner.js
src/tests/export/cronJob.test.js
src/tests/export/export.patient.test.js
src/tests/export/export.test.js
src/tests/export/export.trigger.test.js
src/utils/k8sClient.js

Endpoint: <base_url>4_0_0/Patient/$export?_type=Appointment&loglevel=debug&requestsMemory=3&ttlsecondsAfterFinished=5&patientReferenceBatchSize=20&fetchResourceBatchSize=30&uploadPartSize=40
ExportStatus resource created:
{
"_id": {
"$oid": "668ff60509d2f2fd66ea1f3c"
},
"id": "8b402cf6-c6a3-491f-9df9-73eaa2beccae",
"resourceType": "ExportStatus",
"meta": {
"versionId": "1",
"lastUpdated": {
"$date": "2024-07-11T15:11:01.000Z"
},
"source": "https://www.icanbwell.com/fhir-server",
"security": [
{
"system": "https://www.icanbwell.com/owner",
"code": "bwell"
},
{
"system": "https://www.icanbwell.com/sourceAssigningAuthority",
"code": "bwell"
}
]
},
"identifier": [
{
"id": "sourceId",
"system": "https://www.icanbwell.com/sourceId",
"value": "8b402cf6-c6a3-491f-9df9-73eaa2beccae"
},
{
"id": …

EFS-1058: Added option to pass context for export job's pod creation & script

---

package.json
src/middleware/graphql/graphqlServer.js
src/middleware/graphql/graphqlServerV2.js
src/operations/fhirOperationsManager.js
src/tests/common.js
src/tests/practitioner/search_by_multiple_ids_ndjson/search_by_multiple_ids_ndjson.test.js
src/utils/fhirRequestInfo.js
yarn.lock

Reverts icanbwell/fhir-server#1708

Revert "handle multiple accept types"

---

src/dd_instrumentation.js

Reverts icanbwell/fhir-server#1716

Revert "EFS-1170: Removed ignored urls from dd_instrumentation"

---

Dockerfile

see https://icanbwell.atlassian.net/wiki/spaces/ENTARCH/pages/4738220033/How+to+use+Alpine+docker+images

CIE-5665 update Dockerfile to start using public ecr alpine

---

src/fhir/generator/fhir_xml_schema_parser.py
src/middleware/graphql/graphqlServerV2.js

Reverts icanbwell/fhir-server#1781

Revert "EFS-1360 Remove subgraph"

---

src/operations/fhirOperationsManager.js
src/operations/summary/summary.js
src/operations/summary/summaryHelper.js
src/operations/summary/summaryRelatedResourceManager.js
src/operations/summary/summaryRelatedResourcesMapper.js
src/tests/summary/summary.test.js

Implement the `$summary` operation in FHIR.
* **Add `summary.js`**: Implement the `$summary` operation following the structure of `$everything`. Include logic for retrieving summarized resources and add necessary imports and exports.
* **Add `summaryHelper.js`**: Implement helper functions for the `$summary` operation. Include logic for summarizing resources and add necessary imports and exports.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/icanbwell/fhir-server/pull/1879?shareId=d58f059f-a0d7-47ee-9f8b-b94dd4bcfe7c).

Implement $summary operation in FHIR

---

.github/workflows/publish_docker.yml
src/fhir/generator/generate_classes.py
src/fhir/generator/generate_classes_index.py
src/fhir/generator/generate_classes_serializer_index.py
src/fhir/generator/generate_graphql_classes.py
src/fhir/generator/generate_graphqlv2_classes.py
src/fhir/generator/generate_serializers.py

https://app.aikido.dev/repositories/11914?sidebarIssue=3126739
https://app.aikido.dev/repositories/11914?sidebarIssue=300772

IGNT-200 fix vulnerabilities
