Dockerfile, package.json, src/index.js
* Dockerfile switch to node from npm.  NPM swallows process signals
* added http-terminator to handle network connections during shutdown
=> Graceful Server Shutdown with K8

package-lock.json, package.json, src/profiles.js, src/services/base/base.service.js
- Changes the route for the $graph API endpoint to be in line with the FHIR standard
- Changes config for the pm2 server in dev so that it watches the filesystem and restarts on a change
- Updates the `graph` function so that it will find an id if it is specified via the URL rather than just looking at query parameters
- A couple of minor fixes to comments and log statements
=> Graph route and QoL fixes

src/dist/js/search.js, src/middleware/htmlRenderer.js, src/operations/query/filters/dateTime.js, src/operations/query/r4.js, src/utils/searchForm.util.js, src/views/pages/SearchResult.ejs, src/views/partials/searchForm.ejs
The reason to still use _lastUpdated:below and _lastUpdated:above is to allow a simpler repopulation of the search form values
=> convert _lastUpdated search param to use date type

src/app.js
req.protocol is returning the incorrect value due to the reverse proxy. X-Forwarded-Proto can be set by the reverse proxy to tell the app whether it is https or http or even an invalid name
https://expressjs.com/en/guide/behind-proxies.html
=> ATHD-780: enable access to reverse proxy info

src/createContainer.js, src/tests/dataLayer/databaseBulkInserter/databaseBulkInserter.test.js, src/tests/patient/change_events/change_events.test.js, src/tests/patient/change_events/fixtures/patient/patient1.json, src/tests/patient/change_events/fixtures/person/person1.json, src/tests/patient/change_events/fixtures/person/person1_nolink.json, src/tests/patient/change_events/fixtures/person/person1_withlink.json, src/tests/utils/bwellPersonFinder/bwellPersonFinder.test.js, src/tests/utils/bwellPersonFinder/fixtures/bwellPerson_directLink.json, src/tests/utils/bwellPersonFinder/fixtures/bwellPerson_indirectLink.json, src/tests/utils/bwellPersonFinder/fixtures/linkedPerson1.json, src/tests/utils/bwellPersonFinder/fixtures/linkedPerson1_cycle.json, src/tests/utils/bwellPersonFinder/fixtures/linkedPerson2.json, src/utils/bwellPersonFinder.js, src/utils/changeEventProducer.js
EFS-98
Update patient change events to fire 2 events: 1 for the specific Patient and 1 for the Proxy Patient (based on the linked bwell master person).
=> EFS-98 Publish Patient Change event for Proxy Patient

src/operations/security/scopesManager.js
EFS-105
Update ScopesManager to only perform scope validation if AUTH_ENABLED is true. Otherwise, assume there is not a patient scope
=> Check AUTH_ENABLED before validating scope

src/tests/searchParameters/search_by_proxy_patient/search_by_proxy_patient/fixtures/Observation/observation3.json, src/tests/searchParameters/search_by_proxy_patient/search_by_proxy_patient/fixtures/expected/expectedObservationProxyPatientWithDirectLink.json, src/tests/searchParameters/search_by_proxy_patient/search_by_proxy_patient/search_by_proxy_patient.test.js, src/utils/kafkaClient.js, src/utils/personToPatientIdsExpander.js
EFS-111
Include proxy patient ID in result of rewriting proxy patient ID to associated patient IDs, allowing resources associated directly with the proxy patient ID to be included in the response bundle.
=> EFS-111 add proxy patient ID to proxy rewrite result

src/tests/patient/change_events/change_events.test.js, src/tests/patient/change_events/fixtures/observation/observation2.json, src/utils/changeEventProducer.js
HP-2536
If a sourceType extension is found on a created resource, then add that as a source.type on the generated Patient Change events. This is specifically used so that the cql-engine can publish that an Observation came from it and have the resulting event NOT instigate an additional run of the CQL Engine.
=> HP-2536 Add source type to patient change audit events

src/constants.js, src/middleware/graphql/graphqlServer.js, src/middleware/graphql/graphqlServer1.js, src/routeHandlers/admin.js, src/routeHandlers/fhirServer.js, src/tests/graphql/field_filter/field_filter.test.js
1. `X-REQUEST-ID` was being fetched instead of `x-request-id` from the request headers. Moved it to a constant.
2. Updated a test case to validate it.
=> EFS-132: Fixed x-request-id header fetch

src/middleware/graphql/graphqlServer.js, src/middleware/graphql/graphqlServer1.js, src/operations/fhirOperationsManager.js, src/routeHandlers/admin.js, src/routeHandlers/fhirServer.js, src/tests/graphql/field_filter/field_filter.test.js, src/tests/searchParameters/search_by_name/fixtures/expected/expected_person_lenient_search.json, src/tests/searchParameters/search_by_name/search_by_name.test.js, src/utils/slack.logger.js
`header()` handle case insensitiveness of the http headers while `header[]` object does not.
=> EFS-132: Used express header() func instead of headers object for request

package-lock.json, package.json, src/dataLayer/databaseQueryManager.js, src/graphql/v2/dataSource.js, src/graphql/v2/resolvers/custom/codeSystem.js, src/graphql/v2/schemas/custom/codeSystem.graphql, src/operations/search/searchBundle.js, src/operations/search/searchManager.js, src/tests/graphql/field_filter/field_filter.test.js, src/tests/graphql/field_filter/fixtures/query_getcodesystemcodes_with_filter.graphql, src/utils/graphqlFieldsProjection.js, yarn.lock
**Ticket:** https://icanbwell.atlassian.net/browse/CVP-1668
**Problem:** Fetching specific code from a CodeSystem currently retrieves the whole CodeSystem from the Mongo DB having a large number of codes in it.
**Solution:** Added a new GraphQL query for CodeSystem that uses the Mongo Aggregation pipeline query to filter on the concept code array of the CodeSystem Resource and return the filtered codes only from the DB.
=> CVP-1668: Added get CodeSystem codes graphql query for optimized mongo query

src/operations/search/searchBundle.js
Error:
`AggregateError: Option \"explain\" cannot be used on an aggregate call with writeConcern\n    at SearchBundleOperation.searchBundle (/srv/src/src/operations/search/searchBundle.js:386:19)\n    at async FhirDataSource.getResourcesBundle (/srv/src/src/graphql/v2/dataSource.js:330:24)\n    at async Object.getCodeSystemCodes (/srv/src/src/graphql/v2/resolvers/custom/codeSystem.js:58:20)`
Skipped query explanation for aggregation query. Need to be investigated further for long term fix.
Previous PR: https://github.com/icanbwell/fhir-server/pull/812
=> CVP-1668: Fixed explain error for aggregation query

src/config.js
As per doc: https://www.mongodb.com/docs/atlas/data-federation/supported-unsupported/limitations/
"
Having more than 60 guaranteed simultaneous connections per region to a federated database instance
"
So, updated the Online Archive connection minPool to zero such that it will create a connection on demand and does not create issues while the server startup.
Note: Once we get lots of requests for AuditEvent(60+ concurrent). We have to add rate limit for this individual API. Because online archive does not support:
- Having more than 60 guaranteed simultaneous connections per region to a federated database instance
- Running more than 30 simultaneous queries on your federated database instance
=> EFS-260 Set minminPoolSize for online archive to 0

src/admin/runners/fixMultipleSourceAssigningAuthorityRunner.js, src/admin/scripts/fixMultipleSourceAssigningAuthority.js, src/admin/utils/fixMultipleSourceAssigningAuthority.js, src/preSaveHandlers/handlers/sourceAssigningAuthorityColumnHandler.js, src/tests/admin/runners/fixMultipleSourceAssigningAuthority/fixMultipleSourceAssigningAuthority.test.js, src/tests/admin/runners/fixMultipleSourceAssigningAuthority/fixMultipleSourceAssigningAuthorityPatient.test.js, src/tests/admin/runners/fixMultipleSourceAssigningAuthority/fixtures/Patient/patient1.json, src/tests/admin/runners/fixMultipleSourceAssigningAuthority/fixtures/Patient/patient1_history.json, src/tests/admin/runners/fixMultipleSourceAssigningAuthority/fixtures/expected/expected_patient1.json, src/tests/admin/runners/fixMultipleSourceAssigningAuthority/fixtures/expected/expected_patient1_history.json, src/tests/admin/runners/fixMultipleSourceAssigningAuthority/fixtures/expected/expected_patient1_history_in_database_before_run.json, src/tests/admin/runners/fixMultipleSourceAssigningAuthority/fixtures/expected/expected_patient_1_in_database_before_run.json
1. Fix main collection: `node src/admin/scripts/fixMultipleSourceAssigningAuthority.js --batchSize=10000 --filterRecords`
2. Fix references in other collections: `node src/admin/scripts/fixReferenceSourceAssigningAuthority.js--batchSize=10000 --after <AFTER_DATE>` Choose AFTER_DATE as the start date of the script in step 1.
3. Fix history: `node src/admin/scripts/fixMultipleSourceAssigningAuthorityHistory.js --collections=all --batchSize=10000`
=> EFS-283 Updated presave handler and fixMultipleSourceAssigningAuthority script to set only 1 authority

src/admin/runners/fixReferenceSourceAssigningAuthorityRunner.js
The script will work fine when --preloadCollections parameter is used. But when --preloadCollections is not used, the part of code that sets the references's UUID and authority has issue. UUID is set without the resource type prefix and the authority is not set at all. FIxed that in this PR.
=> EFS-283 Update fixRefences script to update the authority and uuid correctly when cache not used

src/dataLayer/databaseBulkInserter.js, src/utils/auditLogger.js
Reverts icanbwell/fhir-server#1018
Problem:
References of the main resources are resolved in parallel. Even the AuditEvents generated by those referenced resources are added to the same map for the current request. When AuditEvent of one resource type is getting executed, the AuditEvent of another resource type is also being executed to be put into the DB. Since the current AuditEvent does not cleared before the execution of the other AuditEvent, same AuditEvent can be part of both the DB operations.
Solution:
Use lock to flush AuditEvents one at a time i.e insertion of DB operation into the map, its execution and clearing the map should be done one at a time.
Added mutex.runExclusive() to flushAsync() function.
=> Revert "Revert "EFS-303 Created insertOneAuditEventAsync to insert audit event""

src/config.js
KeepAlive option is deprecated and no longer configurable. As per docs, it will be true by default.
For more info about this, check: https://github.com/mongodb/node-mongodb-native/pull/3621
=> EFS-433 Disabling the deprecated keepAlive option in mongoConfig options

.idea/vcs.xml, src/createContainer.js, src/operations/patch/patch.js, src/operations/update/update.js, src/tests/patch/patch/fixtures/ActivityDefinition/activitydefinition4.json, src/tests/patch/patch/fixtures/ActivityDefinition/activitydefinition5.json, src/tests/patch/patch/fixtures/expected/expected_ActivityDefinition5.json, src/tests/patch/patch/fixtures/expected/expected_ActivityDefinitionBwell.json, src/tests/patch/patch/fixtures/expected/expected_ActivityDefinitionMedstar.json, src/tests/patch/patch/fixtures/expected/expected_error_with_multiple_documents.json, src/tests/patch/patch/fixtures/patches/patch3.json, src/tests/patch/patch/patch.test.js, src/tests/patient/search_with_patient_filtering/search_with_patient_filtering.test.js, src/tests/update/put_response/fixtures/ActivityDefinition/activitydefinition4.json, src/tests/update/put_response/fixtures/ActivityDefinition/activitydefinition5.json, src/tests/update/put_response/fixtures/expected/expected_ActivityDefinition5.json, src/tests/update/put_response/fixtures/expected/expected_ActivityDefinitionBwell.json, src/tests/update/put_response/fixtures/expected/expected_ActivityDefinitionMedstar.json, src/tests/update/put_response/fixtures/expected/expected_error_with_multiple_documents.json, src/tests/update/put_response/fixtures/expected/expected_error_without_owner.json, src/tests/update/put_response/put_sourceAssigningAuthority.test.js
1. Consider access tags in the scope to filter the documents.
2. Consider the id and sourceassigningauthority to filter the documents.
3. Test cases.
=> EFS-541 Made owner tag compulsory for update endpoint

src/admin/personMatchManager.js, src/operations/common/resourceValidator.js, src/routeHandlers/smartConfiguration.js, src/strategies/jwt.bearer.strategy.js, src/tests/validate/remote_server/expected/404_from_profile_url.json, src/tests/validate/remote_server/expected/404_from_profile_url_indside_resource.json, src/tests/validate/remote_server/fixtures/invalid_practitioner_1.json, src/tests/validate/remote_server/practitioner_remote_server_by_id.validate.test.js, src/utils/configManager.js, src/utils/digestAuth.js, src/utils/remoteFhirValidator.js
1. Update the error message when we receive 404 while fetching the profile, pass the profile path to make the message unambiguous
2. Add request timeout for superagent
=> EFS-574 Update Error message in  endpoint, mention the path of profie that was not able to fetch

src/middleware/errorHandler.js
- While working on EFS-378, We have integrated Terminus for graceful shutdown and we don’t need this explicit SIGTERM handler anymore. But somehow it was re-introduced by Imran changes.
- https://github.com/icanbwell/fhir-server/pull/1145/files#diff-519678aa4b49c6489b5992f218f138bd96c60e7068003ce00ae497caec9a6935R41-R46
=> EFS-652 Removed explicit duplicate SIGTERM handler

src/fhir/fhirTypesManager.js
This function is [called during arg parsing](https://github.com/icanbwell/fhir-server/blob/main/src/operations/query/r4ArgsParser.js#L161) and seems to be a large bottleneck. See below:
As you can see, this function can take up to 13ms to run. 
If you take a look at getTypeForField ([here](https://github.com/icanbwell/fhir-server/blob/main/src/fhir/fhirTypesManager.js#L22)), you can see that its creating a new array by spreading two other arrays like so. Notice that every time this function is called, 2 or 3 garbage collections happen (the yellow squares under the getTypeForField call).
dataElementMap is the result of Object.entries of [this file](https://github.com/icanbwell/fhir-server/blob/main/src/fhir/generator/json/fhir-generated.field-types.json).
For reference, that file is over …
=> EA-1945 Caches combinedDataElementMap variable

README.md, download_results.md, download_summary.md, package.json, src/converters/baseBundleConverter.js, src/converters/bundleToCsvConverter.js, src/converters/bundleToExcelConverter.js, src/createContainer.js, src/graphs/practitioner/summary.json, src/operations/search/searchManager.js, src/operations/streaming/resourceWriters/fhirResourceExcelWriter.js, src/operations/streaming/resourceWriters/fhirResourceWriterFactory.js, src/operations/summary/summary.js, src/tests/practitioner/search_by_multiple_ids_csv/search_by_multiple_ids.excel.test.js, src/tests/practitioner/search_by_multiple_ids_csv/search_by_multiple_ids_csv.test.js, src/tests/summary/person_or_patient/person_or_patient.csv.test.js, src/tests/summary/person_or_patient/person_or_patient.excel.test.js, src/tests/summary/practitioner/fixtures/practitioner/organization.json, src/tests/summary/practitioner/fixtures/practitioner/practitioner.json, src/tests/summary/practitioner/fixtures/practitioner/practitionerRole.json, src/tests/summary/practitioner/fixtures/practitioner/practitionerRoleDifferentSecurityTag.json, src/tests/summary/practitioner/practitioner.excel.test.js, src/tests/utils/fhirResponseCsvStreamer/fhirResponseCsvStreamer.test.js, src/utils/buffer_to_chunk_transfer_response.js, src/utils/fhirResponseCsvStreamer.js, src/utils/fhirResponseExcelStreamer.js, src/utils/removeUnderscoreProps.js, yarn.lock
This PR updates the fhir-to-csv package and related code to support Excel output formats alongside CSV/TSV. It adjusts import paths, updates asynchronous API calls to synchronous ones where applicable, and integrates new Excel writer logic throughout streaming and conversion files.
Update of the fhir-to-csv dependency and related import paths
Addition of new functionality for handling Excel responses in both production and tests
Minor refactoring in documentation and JSDoc comments
=> Update fhir to csv package

src/operations/merge/merge.js, src/operations/merge/mergeManager.js, src/tests/merge/merge_replace/fixtures/Person/person1.json, src/tests/merge/merge_replace/fixtures/Person/person1_duplicate_phone.json, src/tests/merge/merge_replace/fixtures/expected/expected_Replaced_Phone.json, src/tests/merge/merge_replace/fixtures/expected/expected_merged_Phone.json, src/tests/merge/merge_replace/merge_put_replace_scenario.test.js
Key Changes and Improvements:
Smart Merge Functionality Turn ON/FF
Added a new **`smartMerge`** parameter (**`default: true`)** to control merge behavior
Allows simulating a bulk **`PUT`** operation when **`smartMerge`** is set to **`false`**
Code Modifications:
Updated **`merge.js`** and **`mergeManager.js `** to support the new **`smartMerge`** parameter
Propagated the **`smartMerge`** flag through various merge-related methods
Introduced a new test case to validate the bulk replace scenario
NOTE:  [ResourceMerger]( https://github.com/icanbwell/fhir-server/blob/main/src/operations/common/resourceMerger.js#L363-L366) already supports this functionality; we just needed to disable smart merge so that a patch is generated and the update is applied directly to the resource like in PUT [so …
=> IGNT-158 Support query string for $merge endpoint to disable smart merge

docker-compose.yml
This PR migrates away from Bitnami images and Helm charts due to their deprecation of the public catalog on Sep. 29th, 2025. Only the minimum necessary changes have been made to replace Bitnami dependencies with official alternatives.
- **Docker Images**: Replaced Bitnami images with official alternatives (kafka, redis, mongodb, etc.)
- **Helm Charts**: Updated chart dependencies from charts.bitnami.com to official repositories
- **Volume Paths**: Updated mount paths to match new image structures
- **Default Credentials**: Updated from "bitnami" defaults to standard defaults where applicable
**Please review all Docker and Helm configuration changes carefully** - while only minimum changes were made, teams should verify:
- Local development environments still work correctly
- …
=> CIE-6997: Migrate from Bitnami
